### ISSUE TITLE
Please set up the docs directory to be served as HTML

### ISSUE THREAD

**Issue by lindes** [plewto/CYCO3#1]
Hi Steven,

I saw your announcement for this on the CM mailing list, and came to check it out.  I see you reference the docs directory for full documentation, and I wanted to take a look through there... However, if I click on any of the HTML files, it just shows me github's source viewer for the HTML.

Could you perhaps host the docs on GitHub Pages?

Info on how to do that for an existing tree is here:

https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

That (plus an update to the README to link to that) would, I think, make it much easier to explore this project -- and in my case, see if it's right for me, and in other cases learn to use it properly.

Thanks!

- David

**Comment by plewto** [comment]
Thanks David for the suggestion, it makes perfect sense.    I will be
looking into publishing the docs.  It may take a bit of time though, I am
currently recovering from Covid.

**Comment by lindes** [comment]
Oh wow; I wish you a speedy and complete recovery!  And yeah, cool; whenever you have the chance!  Best!  And thanks for the response.

**Comment by plewto** [comment]
Created separate documentation page at https://plewto.github.io/cyco3-docs/
